### ISSUE TITLE
Uncaught SyntaxError:Unexpected end of JSON input

### ISSUE THREAD

**Issue by rolorogan** [marcjansen/atom-geo-editor#1]
[Enter steps to reproduce below:]

1. Toggle Geo Editor On

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [geo-editor](https://github.com/marcjansen/atom-geo-editor) package, v0.2.1

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%5D%2C%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F7q%2F5xgg037x7rqc76_mkbm_x4x40000gq%2FT%2F%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F7%3A0x0%3A0x0%22%2C%22HOME%22%3A%22%2FUsers%2Fnathan%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.XzhKrgxYkf%2FRender%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.W59FMM4ITF%2FListeners%22%2C%22PATH%22%3A%22%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22LOGNAME%22%3A%22nathan%22%2C%22DISPLAY%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.FMkBs4MUtw%2Forg.macosforge.xquartz%3A0%22%2C%22XPC_SERVICE_NAME%22%3A%22com.github.atom.60832%22%2C%22USER%22%3A%22nathan%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Fnathan%2F.atom%22%7D%2C%22appVersion%22%3A%221.13.0%22%2C%22atomHome%22%3A%22%2FUsers%2Fnathan%2F.atom%22%7D:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at bn (/Users/nathan/.atom/packages/geo-editor/lib/ol.js:401:466)
    at un.k.Fa (/Users/nathan/.atom/packages/geo-editor/lib/ol.js:401:632)
    at GeoEditorView.updateMap (/Users/nathan/.atom/packages/geo-editor/lib/geo-editor-view.js:164:48)
    at Object.toggle (/Users/nathan/.atom/packages/geo-editor/lib/geo-editor.js:46:26)
    at atom-workspace.geoEditorToggle (/Users/nathan/.atom/packages/geo-editor/lib/geo-editor.js:24:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1175:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:319:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:01.5.0 geo-editor:toggle (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0 (inactive)
angularjs, v0.3.5 (active)
color-picker, v2.2.4 (active)
compare-files, v0.8.0 (active)
css-color-underline, v1.0.1 (active)
geo-editor, v0.2.1 (inactive)
seti-ui, v1.4.0 (active)
webbox-color, v0.5.9 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by marcjansen** [comment]
Thanks for the report. I cannot promise to have a look, but do you have the GeoJSON file you toggled the editor for?

**Comment by marcjansen** [comment]
Did you toggle the editor on while editing an empty file? I can then reproduce the error you mention.

![image](https://cloud.githubusercontent.com/assets/227934/24007978/837875b2-0a70-11e7-9e52-eba81fa15ae1.png)

This is not supposed to work right now

**Comment by rolorogan** [comment]
The error was appearing on an empty file and a file with data already in it.

I can't reproduce the error now and the package seems to be working as expected.

Thanks for looking.
